#!/usr/bin/ruby

####
###
##
#  This is the executable file
##
###
#### v 0.6

Dir[File.dirname(__FILE__) + '/lib/*.rb'].each {|file| require file }

####
###
##
# Initialize handlers and map including player inventory
#

include Screen
include Messager
include Map

Map.read_map('map.xml')
Screen.start(Map.name)

####
###
##
# Start GUI
Tk.mainloop()

####
###
##
# That's it...

exit true
